### ISSUE TITLE
qmlscene on resin.io

### ISSUE THREAD

**Issue by buildog** [theshadowx/qt_raspbian#1]
Hi @theshadowx

from the docker image I'm trying to launch a qmlscene, could you tell me if it's possible cause actually I got a `bash: qmlscene: command not found` ?

**Comment by theshadowx** [comment]
Hi @buildog 
You have received this error message, because Qt bin folder is not exposed in the environment PATH.
You should either use the full path : ```/usr/local/qt5/bin/qmlscene```
or add the path :  export PATH=/usr/local/qt5/bin/:$PATH

**Comment by buildog** [comment]
Great thanks @theshadowx ,

one more thing, I'm using resin and it look like I've to somehow bind the display which is the HDMI port, is there a simple way to do it inside the docker file ?

**Comment by theshadowx** [comment]
From what I understood, you want to open a gui app from Docker container, is that right?

To be done, you should add in the docker run command : -e Display -v /tmp/.X11-unix/:/tmp/.X11-unix/ -v $HOME/.Xauthority:/home/developer/.Xauthority



![co9xlkrwwaaqksx](https://cloud.githubusercontent.com/assets/976569/20891480/aa80f570-bb02-11e6-8d8e-fd4e71e71f24.jpg)

**Comment by buildog** [comment]
no, I'd like to use QT5 on the Pi to launch a webview (fullscreen webkiosk) 


````
FROM theshadowx/rpi-qt:wheezy_qt5.5

COPY index.qml ./
COPY launch.sh ./
ENV INITSYSTEM=on

CMD ["bash", "launch.sh"]
````

***launch.sh***

```bash
#!/bin/bash

export QT_QPA_PLATFORM=eglfs
export LD_LIBRARY_PATH=/opt/vc/lib
export QT_QPA_EGLFS_HIDECURSOR=1
export DISPLAY=:0

/usr/local/qt5/bin/qmlscene  /index.qml
```

***index.qml***

````
import QtQuick 2.2
import QtQuick.Window 2.1
import QtWebKit 3.0

Window {
    visible: true
    width: 380
    height: 380

    WebView {
        url: 'https://github.com'
    }
}
```

**Comment by buildog** [comment]
So from this setup I got an error `Could not open display` , don't know why :)

**Comment by buildog** [comment]
I think problem is because it's a build of Qt5 with support for both eglfs and X11. Even if I pass the --platform argument it didn't work. I had to rebuild with only eglfs support.

On the other hand this did not include qtWebkit module. 

Anyway, thanks @theshadowx

**Comment by theshadowx** [comment]
Yes indeed, the QtWebKit module wasn't included.

I just noticed that eglfs Raspberry Pi , was enabled :
```
  QPA backends: 
    DirectFB ............. no
    EGLFS ................ yes
      EGLFS i.MX6....... . no
      EGLFS KMS .......... no
      EGLFS Mali ......... no
      EGLFS Raspberry Pi . no
      EGLFS X11 .......... yes
    LinuxFB .............. yes
    XCB .................. yes (system library)
      EGL on X ........... yes
      GLX ................ yes
      MIT-SHM ............ yes
      Xcb-Xlib ........... yes
      Xcursor ............ yes (loaded at runtime)
      Xfixes ............. yes (loaded at runtime)
      Xi ................. no
      Xi2 ................ yes
      Xinerama ........... yes (loaded at runtime)
      Xrandr ............. yes (loaded at runtime)
      Xrender ............ yes
      XKB ................ no
      XShape ............. yes
      XSync .............. yes
      XVideo ............. yes

```
